### ISSUE TITLE
confusion about max_empirical_losses in trainer.py

### ISSUE THREAD

**Issue by Lihengwannafly** [swisscom/ai-research-mamo-framework#4]
In trainer.train(), we train the model by batch, and duraing the training process in a batch , wo also compute max_empirical_losses by batch.  Does it means that we compute max_empirical_losses time-expensively?

**Comment by blagojce95** [comment]
We only compute the max_empirical_losses once, when the trainer object is initialized.

1. When you create a new trainer object [for example: trainer = Trainer()] the  __init__ constructor is called from the trainer.py script.
2. The constructor calls the self._init_objects() method.
3. This method calls the self._compute_max_empirical_losses() which computes the max empirical losses before calling the trainer.train() method.

The assumption is that the max empirical losses are a good approximation for the theoretical max losses, and competing them once is enough. Also the assumption that the ratio between the two objectives won't change during the training process.

**Comment by Lihengwannafly** [comment]
> We only compute the max_empirical_losses once, when the trainer object is initialized.
> 
> 1. When you create a new trainer object [for example: trainer = Trainer()] the  **init** constructor is called from the trainer.py script.
> 2. The constructor calls the self._init_objects() method.
> 3. This method calls the self._compute_max_empirical_losses() which computes the max empirical losses before calling the trainer.train() method.
> 
> The assumption is that the max empirical losses are a good approximation for the theoretical max losses, and competing them once is enough. Also the assumption that the ratio between the two objectives won't change during the training process.

Thanks for your reply, I review the code again and found that I made a mistake
